- name: Crea Cluster OKE
  hosts: localhost
  connection: local

  vars_files: vault.yaml


  tasks:
    - block:
        - name: Lista Todas las VCNs
          oracle.oci.oci_container_engine_cluster_facts:
             compartment_id: "{{ compartment_ocid }}"
             name: "{{ cluster_name }}"
          register: resultado
       
        - set_fact:
            cluster_id: "{{ resultado.clusters[0].id }}"

        - name: Create kubeconfig
          oracle.oci.oci_container_engine_kubeconfig:
            cluster_id: "{{ cluster_id }}"
          register: resultado
        
        - name: Save to kubeconfig file path
          copy:
            content: "{{ resultado.kubeconfig }}"
            dest: "{{ kubeconfig_path }}"

      rescue:
      - fail:
          msg: "ERROR, No se logro Crear Cluster OKE"
